version: '3.8'

volumes:
  cuda:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jorge/Documents/spacepg

services:
  api-pycuda:
    image: cuda-filters
    ports:
      #- "5000:5000"
      - "5000:5000"
    networks:
      - datalogger_net
    volumes:
      - cuda:/app/data  # Ajusta si quieres que acceda al volumen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia  # Este es esencial para docker-compose clásico


  webflux:
    image: webflux
    ports:
      - "8080:8080"
    # depends_on:
    #   - cuda-filters
      #- "5173:5173"
    volumes:
      - /home/jorge/Documents/Backend/api-webflux/src/main/java/resources/firebase/keyFirebase.json:/app/keyFirebase.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keyFirebase.json
    networks:
      - datalogger_net

  

networks:
  datalogger_net:
    driver: bridge